### ISSUE TITLE
[Edited]

### ISSUE THREAD

**Issue by AndreiD** [ora-io/awesome-uniswap-hooks#69]

**Comment by AndreiD** [comment]
oh? so you're active now? :))

**Comment by fewwwww** [comment]
Hi @AndreiD

Just to clarify a few points:
1. This repo is actively maintained, with the last commit made three weeks ago, so it’s not "dead".
2. Since this is a crypto-related repo, adding external links in GitHub issues isn’t best practice. Such actions, even if well-intended, can sometimes lead to scams. That’s why the external link was edited out.
3. I encourage contributions to the repo. I noticed your last contribution wasn’t merged, which might be why you’re upset and calling the repo "dead." However, instead of forking the repo, opening a separate repository while copying most of the content without attribution to the existing 11 original contributors can lead to unnecessary fragmentation of information, which is not helpful for the community.

**Comment by AndreiD** [comment]
to me is clear that this repo is dead. this is why I will continue this repo's work. it's ok, I had repos to that I left to die. No need to explain yourself, you're not 7
